swagger: "2.0"
info:
  version: 1.0.1
  title: Swagger Store
  description: This is a sample server Petstore server.
paths:
  /api/products:
    get: 
      summary: Lay danh sach san pham
      responses: 
        "200": 
          description: Lay danh sach san pham thanh cong
        "400": 
          description: Lay danh sach san pham khong thanh cong
  /api/product/{id}:
    get:
      summary: Tim kiem san pham 
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
  /api/product/{userId}:
    post: 
      summary: Them san pham
      parameters:
      - name: "userId"
        in: "path"
        description: "ID User Admin san pham"
        required: true
        type: "string"
      - name: "name"
        in: "formData"
        description: "Updated name of the pet"
        required: true
        type: "string"
      - name: "price"
        in: "formData"
        description: "Updated price of the pet"
        required: true
        type: "integer"
      - name: "category"
        in: "formData"
        description: "Updated category of the pet"
        required: true
        type: "string"
      - name: "description"
        in: "formData"
        description: "Updated description of the pet"
        required: false
        type: "string"
      responses:
        "405":
          description: "Invalid input"
  /api/product/{id}/{userId}:
    put: 
      summary: Cap nhat san pham
      parameters:
        - name: "id"
          in: "path"
          description: "ID san pham"
          required: true
          type: "string"
        - name: "userId"
          in: "path"
          description: "ID User Admin san pham"
          required: true
          type: "string"
        - name: "name"
          in: "formData"
          description: "Updated name of the pet"
          required: true
          type: "string"
        - name: "price"
          in: "formData"
          description: "Updated price of the pet"
          required: true
          type: "integer"
        - name: "category"
          in: "formData"
          description: "Updated category of the pet"
          required: true
          type: "string"
        - name: "description"
          in: "formData"
          description: "Updated description of the pet"
          required: false
          type: "string"
      responses:
        "405":
          description: "Invalid input"



schema:
  product:
    properties: 
      name:
        type: string
        minLength: 5
      price: 
        type: integer
      category:
        type: string
    required:
      - name
      - price
      - category
